name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo apt update
          sudo apt install curl mtools squashfs-tools grub-pc-bin grub-efi xorriso debootstrap -y
          sudo bash build.sh
          sudo mkdir -p /output
          sudo mv *.iso /output/pardus-21.x-32bit.iso


      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "main"
          prerelease: false
          title: "21.x stable"
          files: |
            /output/*

